project:
  type: website

website:
  title: "testpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: post.qmd
        text: Post

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



